import NextHead from "next/head";

export default function Head() {
  return (
    <NextHead>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=2.0"
      />
    </NextHead>
  );
}
